### ISSUE TITLE
Rewriting Files Doesn't Work

### ISSUE THREAD

**Issue by DiceAndEasy** [BlitzKraig/fvtt-VoiceActor#14]
If you try to rewrite a file, the recording will work and you'll get the notification that the new file has been saved, but when you press play, the old audio file gets played. I'm not sure if the new file is saved at all.

I'm using FoundryVTT through ForgeVTT.

FoundryVTT version: 0.8.9
VoiceActor version: 0.1.2

**Comment by Argonaut13** [comment]
Yeh, I get the same issue. I think this module is proving too much hassle to keep updating. Last update was in August...

**Comment by BlitzKraig** [comment]
Fixed in 0.2.0

**Comment by DiceAndEasy** [comment]
Thanks @BlitzKraig !

I updated and checked and the issue still persists, unfortunately. I overwrote the voice file, waited for 5+ minutes but it still plays the first recording and not the new one. When you record the new version, you do still get a message that the new file was saved but it doesn't seem to get used.

Foundry version: 9 (latest stable)
VoiceActor version: 0.2.0

**Comment by BlitzKraig** [comment]
Can you send the filenames so I can run some tests?On 27 Apr 2022 09:18, funwithfondue ***@***.***> wrote:
Thanks @BlitzKraig !
I updated and checked and the issue still persists, unfortunately. I overwrote the voice file, waited for 5+ minutes but it still plays the first recording and not the new one. When you record the new version, you do still get a message that the new file was saved but it doesn't seem to get used.
Foundry version: 9 (latest stable)
VoiceActor version: 0.2.0

**Comment by BlitzKraig** [comment]
Confirmed issue when running via Forge. Investigating

**Comment by BlitzKraig** [comment]
Fixed in `0.2.1`

**Comment by DiceAndEasy** [comment]
Tested it and overwriting is working as intended now.

Thank you very much for fixing this!

**Comment by Argonaut13** [comment]
No idea if I can just reply via email, but let's try. That is probably an
issue due to how Forge handles overwriting files. For example, if you
upload an image with the same name as another, it can take up to an hour
for the new image to actually replace the old one.
